# Generated by Django 5.0.7 on 2024-12-28 18:11

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='profiles/user-default.png', force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to='profiles/'),
        ),
    ]
